### PR TITLE
Updated PASCAL with different method and fixed 404 link not found in index folders

### PR DESCRIPTION
**Pull request by rinaldipratama**
1. Deleted unnecessary files
2. Updated PASCAL with different method
3. Fixed link 404 not found in index folders for COFFEESCRIPT

### CODE REVIEW

**Comment by afdulfauzan** [comment]
fix the conflict first, Thx

**Comment by rinaldipratama** [comment]
Done.

**Comment by afdulfauzan** [comment]
Thank you bro, you contributed a lot to this project

**Comment by rinaldipratama** [comment]
you're welcome bro, I'm glad to help in this project 😄

**Pull request merged**
